postgres:
  image: postgres
node:
  build: .
  volumes:
    - .:/usr/src/app
  links:
    - postgres
  environment:
    TEST_DATABASE_URL: postgres://postgres@postgres/refresh-token-test
psql:
  image: postgres
  links:
    - postgres
  command: psql
